// <auto-generated />
using System;
using EcoCheck.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoCheck.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002003521_AddOptionalRegion")]
    partial class AddOptionalRegion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoCheck.Api.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("Category", "DisplayOrder")
                        .HasDatabaseName("ix_questions_category_display_order");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Water",
                            DisplayOrder = 1,
                            IsActive = true,
                            Text = "Quanto tempo, em média, dura o seu banho?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Water",
                            DisplayOrder = 2,
                            IsActive = true,
                            Text = "Você fecha a torneira enquanto escova os dentes, ensaboa as mãos ou a louça?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Water",
                            DisplayOrder = 3,
                            IsActive = true,
                            Text = "Quando aparece um vazamento em casa (torneira pingando, descarga escorrendo), em quanto tempo ele costuma ser resolvido?"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Water",
                            DisplayOrder = 4,
                            IsActive = true,
                            Text = "Você reaproveita água (da chuva, do enxágue da máquina de lavar etc.) para limpar o chão, regar plantas ou dar descarga?"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Water",
                            DisplayOrder = 5,
                            IsActive = true,
                            Text = "Como você costuma lavar calçadas, quintais ou veículos?"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Energy",
                            DisplayOrder = 6,
                            IsActive = true,
                            Text = "Com que frequência você apaga as luzes ao sair de um cômodo?"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Energy",
                            DisplayOrder = 7,
                            IsActive = true,
                            Text = "Qual tipo de lâmpada predomina onde você mora?"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Energy",
                            DisplayOrder = 8,
                            IsActive = true,
                            Text = "Com que frequência você deixa aparelhos (TV, computador, videogame, carregadores) ligados ou em espera sem necessidade?"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Energy",
                            DisplayOrder = 9,
                            IsActive = true,
                            Text = "Ao usar ar-condicionado ou aquecedor, você mantém portas e janelas fechadas e evita temperaturas extremas?"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Energy",
                            DisplayOrder = 10,
                            IsActive = true,
                            Text = "Ao comprar eletrodomésticos, você verifica a eficiência energética na etiqueta do Inmetro ou o Selo Procel?"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Waste",
                            DisplayOrder = 11,
                            IsActive = true,
                            Text = "Você separa os materiais recicláveis (papel, plástico, metal, vidro) do lixo comum?"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Waste",
                            DisplayOrder = 12,
                            IsActive = true,
                            Text = "Como você descarta pilhas, baterias e eletrônicos sem uso?"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Waste",
                            DisplayOrder = 13,
                            IsActive = true,
                            Text = "Com que frequência você usa itens descartáveis, como copos, talheres, canudos e sacolas plásticas?"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Waste",
                            DisplayOrder = 14,
                            IsActive = true,
                            Text = "Você reutiliza embalagens, potes, sacolas ou outros materiais antes de descartá-los?"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Waste",
                            DisplayOrder = 15,
                            IsActive = true,
                            Text = "Você procura evitar o desperdício de alimentos (planejando compras, aproveitando sobras)?"
                        },
                        new
                        {
                            Id = 16,
                            Category = "ConsumptionAndMobility",
                            DisplayOrder = 16,
                            IsActive = true,
                            Text = "Qual meio de transporte você mais utiliza nos deslocamentos do dia a dia?"
                        },
                        new
                        {
                            Id = 17,
                            Category = "ConsumptionAndMobility",
                            DisplayOrder = 17,
                            IsActive = true,
                            Text = "Antes de comprar algo novo, você considera se realmente precisa, ou se pode consertar, pegar emprestado ou comprar usado?"
                        },
                        new
                        {
                            Id = 18,
                            Category = "ConsumptionAndMobility",
                            DisplayOrder = 18,
                            IsActive = true,
                            Text = "Você leva garrafa, caneca ou sacola reutilizável quando sai de casa?"
                        },
                        new
                        {
                            Id = 19,
                            Category = "ConsumptionAndMobility",
                            DisplayOrder = 19,
                            IsActive = true,
                            Text = "Com que frequência você busca informações sobre o impacto ambiental dos produtos e serviços que consome?"
                        },
                        new
                        {
                            Id = 20,
                            Category = "ConsumptionAndMobility",
                            DisplayOrder = 20,
                            IsActive = true,
                            Text = "Em passeios por parques, praias, rios ou trilhas, você recolhe seu lixo e evita danificar a natureza?"
                        });
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int?>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_options_question_id");

                    b.ToTable("question_options", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_options_points", "points IS NULL OR (points >= 0 AND points <= 4)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 11,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 1,
                            Text = "Até 5 minutos"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 1,
                            Text = "De 5 a 10 minutos"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 1,
                            Text = "De 10 a 15 minutos"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 1,
                            Text = "De 15 a 20 minutos"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 1,
                            Text = "Mais de 20 minutos"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 2,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 2,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 2,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 2,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 2,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 3,
                            Text = "Em poucos dias"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 2,
                            Points = 2,
                            QuestionId = 3,
                            Text = "Em algumas semanas"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 3,
                            Points = 1,
                            QuestionId = 3,
                            Text = "Demora meses"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 4,
                            Points = 0,
                            QuestionId = 3,
                            Text = "Normalmente não é resolvido"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 5,
                            QuestionId = 3,
                            Text = "Nunca percebi vazamentos / não sei"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 4,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 4,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 4,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 4,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 4,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 6,
                            QuestionId = 4,
                            Text = "Não tenho essa possibilidade onde moro"
                        },
                        new
                        {
                            Id = 51,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 5,
                            Text = "Com balde, pano ou vassoura, sem mangueira"
                        },
                        new
                        {
                            Id = 52,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 5,
                            Text = "Com mangueira com esguicho que interrompe o fluxo"
                        },
                        new
                        {
                            Id = 53,
                            DisplayOrder = 3,
                            Points = 1,
                            QuestionId = 5,
                            Text = "Com mangueira aberta por pouco tempo"
                        },
                        new
                        {
                            Id = 54,
                            DisplayOrder = 4,
                            Points = 0,
                            QuestionId = 5,
                            Text = "Com mangueira aberta durante toda a limpeza"
                        },
                        new
                        {
                            Id = 55,
                            DisplayOrder = 5,
                            QuestionId = 5,
                            Text = "Não faço esse tipo de limpeza"
                        },
                        new
                        {
                            Id = 61,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 6,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 62,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 6,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 63,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 6,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 64,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 6,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 65,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 6,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 71,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 7,
                            Text = "Todas ou quase todas são LED"
                        },
                        new
                        {
                            Id = 72,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 7,
                            Text = "A maioria é LED"
                        },
                        new
                        {
                            Id = 73,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 7,
                            Text = "Cerca de metade é LED"
                        },
                        new
                        {
                            Id = 74,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 7,
                            Text = "Poucas são LED"
                        },
                        new
                        {
                            Id = 75,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 7,
                            Text = "Nenhuma é LED"
                        },
                        new
                        {
                            Id = 76,
                            DisplayOrder = 6,
                            QuestionId = 7,
                            Text = "Não sei"
                        },
                        new
                        {
                            Id = 81,
                            DisplayOrder = 1,
                            Points = 0,
                            QuestionId = 8,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 82,
                            DisplayOrder = 2,
                            Points = 1,
                            QuestionId = 8,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 83,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 8,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 84,
                            DisplayOrder = 4,
                            Points = 3,
                            QuestionId = 8,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 85,
                            DisplayOrder = 5,
                            Points = 4,
                            QuestionId = 8,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 91,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 9,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 92,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 9,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 93,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 9,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 94,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 9,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 95,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 9,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 96,
                            DisplayOrder = 6,
                            QuestionId = 9,
                            Text = "Não uso ar-condicionado nem aquecedor"
                        },
                        new
                        {
                            Id = 101,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 10,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 102,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 10,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 103,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 10,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 104,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 10,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 105,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 10,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 106,
                            DisplayOrder = 6,
                            QuestionId = 10,
                            Text = "Não costumo comprar eletrodomésticos"
                        },
                        new
                        {
                            Id = 111,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 11,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 112,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 11,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 113,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 11,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 114,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 11,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 115,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 11,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 121,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 12,
                            Text = "Levo a pontos de coleta ou devolvo à loja/fabricante"
                        },
                        new
                        {
                            Id = 122,
                            DisplayOrder = 2,
                            Points = 2,
                            QuestionId = 12,
                            Text = "Guardo até encontrar um ponto de coleta"
                        },
                        new
                        {
                            Id = 123,
                            DisplayOrder = 3,
                            Points = 1,
                            QuestionId = 12,
                            Text = "Às vezes no lixo comum, às vezes em ponto de coleta"
                        },
                        new
                        {
                            Id = 124,
                            DisplayOrder = 4,
                            Points = 0,
                            QuestionId = 12,
                            Text = "No lixo comum"
                        },
                        new
                        {
                            Id = 125,
                            DisplayOrder = 5,
                            QuestionId = 12,
                            Text = "Ainda não precisei descartar"
                        },
                        new
                        {
                            Id = 131,
                            DisplayOrder = 1,
                            Points = 0,
                            QuestionId = 13,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 132,
                            DisplayOrder = 2,
                            Points = 1,
                            QuestionId = 13,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 133,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 13,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 134,
                            DisplayOrder = 4,
                            Points = 3,
                            QuestionId = 13,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 135,
                            DisplayOrder = 5,
                            Points = 4,
                            QuestionId = 13,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 141,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 14,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 142,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 14,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 143,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 14,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 144,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 14,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 145,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 14,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 151,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 15,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 152,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 15,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 153,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 15,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 154,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 15,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 155,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 15,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 161,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 16,
                            Text = "A pé ou de bicicleta"
                        },
                        new
                        {
                            Id = 162,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 16,
                            Text = "Transporte público"
                        },
                        new
                        {
                            Id = 163,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 16,
                            Text = "Carona ou transporte compartilhado"
                        },
                        new
                        {
                            Id = 164,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 16,
                            Text = "Carro, moto ou aplicativo individual"
                        },
                        new
                        {
                            Id = 165,
                            DisplayOrder = 5,
                            QuestionId = 16,
                            Text = "Quase não me desloco (estudo/trabalho em casa)"
                        },
                        new
                        {
                            Id = 171,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 17,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 172,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 17,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 173,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 17,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 174,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 17,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 175,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 17,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 181,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 18,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 182,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 18,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 183,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 18,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 184,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 18,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 185,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 18,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 191,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 19,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 192,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 19,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 193,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 19,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 194,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 19,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 195,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 19,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 201,
                            DisplayOrder = 1,
                            Points = 4,
                            QuestionId = 20,
                            Text = "Sempre"
                        },
                        new
                        {
                            Id = 202,
                            DisplayOrder = 2,
                            Points = 3,
                            QuestionId = 20,
                            Text = "Frequentemente"
                        },
                        new
                        {
                            Id = 203,
                            DisplayOrder = 3,
                            Points = 2,
                            QuestionId = 20,
                            Text = "Às vezes"
                        },
                        new
                        {
                            Id = 204,
                            DisplayOrder = 4,
                            Points = 1,
                            QuestionId = 20,
                            Text = "Raramente"
                        },
                        new
                        {
                            Id = 205,
                            DisplayOrder = 5,
                            Points = 0,
                            QuestionId = 20,
                            Text = "Nunca"
                        },
                        new
                        {
                            Id = 206,
                            DisplayOrder = 6,
                            QuestionId = 20,
                            Text = "Não costumo fazer esse tipo de passeio"
                        });
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.SurveyAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionOptionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_option_id");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_response_id");

                    b.HasKey("Id")
                        .HasName("pk_survey_answers");

                    b.HasIndex("QuestionOptionId")
                        .HasDatabaseName("ix_survey_answers_question_option_id");

                    b.HasIndex("QuestionId", "QuestionOptionId")
                        .HasDatabaseName("ix_survey_answers_question_id_question_option_id");

                    b.HasIndex("SurveyResponseId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_survey_answers_survey_response_id_question_id");

                    b.ToTable("survey_answers", (string)null);
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.SurveyCategoryScore", b =>
                {
                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("survey_response_id");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("SurveyResponseId", "Category")
                        .HasName("pk_survey_category_scores");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_survey_category_scores_category");

                    b.ToTable("survey_category_scores", (string)null);
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<int>("QuestionnaireVersion")
                        .HasColumnType("integer")
                        .HasColumnName("questionnaire_version");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_survey_responses");

                    b.HasIndex("Classification")
                        .HasDatabaseName("ix_survey_responses_classification");

                    b.HasIndex("CountryCode", "StateCode")
                        .HasDatabaseName("ix_survey_responses_country_code_state_code");

                    b.ToTable("survey_responses", (string)null);
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.QuestionOption", b =>
                {
                    b.HasOne("EcoCheck.Api.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("EcoCheck.Api.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_answers_questions_question_id");

                    b.HasOne("EcoCheck.Api.Entities.QuestionOption", "QuestionOption")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_answers_question_options_question_option_id");

                    b.HasOne("EcoCheck.Api.Entities.SurveyResponse", "SurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_survey_answers_survey_responses_survey_response_id");

                    b.Navigation("Question");

                    b.Navigation("QuestionOption");

                    b.Navigation("SurveyResponse");
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.SurveyCategoryScore", b =>
                {
                    b.HasOne("EcoCheck.Api.Entities.SurveyResponse", "SurveyResponse")
                        .WithMany("CategoryScores")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_survey_category_scores_survey_responses_survey_response_id");

                    b.Navigation("SurveyResponse");
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("EcoCheck.Api.Entities.SurveyResponse", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("CategoryScores");
                });
#pragma warning restore 612, 618
        }
    }
}
